### ISSUE TITLE
[FEATURE] [FRONTEND]  Standardize bootstrap styles and UI components

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/swag#856]
### Describe the user story:
Wikonnect uses Bootstrap 4 as it's primary UI kit. 
Currently, bootstrap components and styles are provided by `ember-bootstrap` package and by CDN assets on index.html. Everything should be standardized to  ensure consistency  and improve/simplify updates. 

The `ember-bootstrap` components should be utilized whenever possible. The UI kit styles should be imported from `bootstrap` package to ease customization.

### Tasks (where applicable)

- [ ]  Migrate all `bootstrap.js`  based components to `ember-bootstrap` based components
- [ ]  Import bootstrap styles 
- [ ]  Remove JQuery and bootstrap cdn assets from index.html

### Acceptance Criteria

On all UI components,
- [ ] Current UI/UX functionality should be maintained 
- [ ] Current UI look and feel should be maintained
