### ISSUE TITLE
[FEATURE] [FRONTEND] Styles Cleanup

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/swag#857]
### Describe the user story:
Although Wikonnect utilizes the Sass preprocessor, the functionality is not fully exploited at the moment. 
The is no consistent use of colors/themes across various components making it difficult to handle #94. 

Component-specific styles should utilize CSS modules provided by `ember-css-modules` package.

### Tasks (where applicable)

- [ ] Provide colors via centralized variables
- [ ] Centralize teach and learner color themes - to be swapped with css variables

### Acceptance Criteria

On all UI components,

- [ ] Current UI/UX functionality should be maintained
- [ ] Current UI look and feel should be maintained
