### ISSUE TITLE
[FEATURE] [FRONTEND] lazy load translations

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/swag#858]
### Describe the user story:
 By default` ember-intl `bundles all translations in wikonnect.js. In an effort to reduce the final production bundle size,  translations should be lazy loaded.

### Tasks (where applicable)

- [ ]  A guide is available [here](https://ember-intl.github.io/ember-intl/docs/guide/asynchronously-loading-translations)

### Tests (where applicable)

- [ ]  Selecting language on main navbar should load/switch to respective translations 

### Acceptance Criteria

- [ ] English translation works
- [ ] Swahili translations works
