### ISSUE TITLE
[FEATURE] [FRONTEND] Persist language selection

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/swag#859]
### Describe the user story:
Currently, when a user selects the Swahili language, the current page text is translated as expected until they navigate to a different path/route. Selected language should persist across route navigation and page reloads (on the same browser). 

~~If the user is logged in, selected language `should` persist across sessions.~~

### Tasks (where applicable)

- [ ]  

### Tests (where applicable)

- [ ]  User can change the app language
- [ ] Selected language is persisted across routes
- [ ] ~~Last selected language is persisted across user sessions~~

### Acceptance Criteria

- [ ] Selected language is persisted across routes on same browser (for both logged in and anonymous users).
