### ISSUE TITLE
[FRONTEND] Code cleanup

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/swag#860]
## Tasks
- [ ] Remove `ember-tag-input` package
- [ ] Consistent use of `@config` service
- [ ] Remove `ember-ajax` package
- [ ] Use `ember changeset` to validate forms
